apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cv9j13rph-go
  janus-idp.io/tekton: cv9j13rph-go
  backstage.io/kubernetes-id: cv9j13rph-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cv9j13rph-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
